In [1]:
# Import libraries
import pandas as pd
import numpy as np

In [2]:
filename = 'data/car_financing.xlsx'
df = pd.read_excel(filename)

## Basic Operations

1. Assure that you have correctly loaded the data. 
2. See what kind of data you have. 
3. Check the validity of your data.

### Viewing the first and last 5 rows

In [3]:
help(df.head)

Help on method head in module pandas.core.generic:

head(n: 'int' = 5) -> 'Self' method of pandas.core.frame.DataFrame instance
    Return the first `n` rows.

    This function returns the first `n` rows for the object based
    on position. It is useful for quickly testing if your object
    has the right type of data in it.

    For negative values of `n`, this function returns all rows except
    the last `|n|` rows, equivalent to ``df[:n]``.

    If n is larger than the number of rows, this function returns all rows.

    Parameters
    ----------
    n : int, default 5
        Number of rows to select.

    Returns
    -------
    same type as caller
        The first `n` rows of the caller object.

    See Also
    --------
    DataFrame.tail: Returns the last `n` rows.

    Examples
    --------
    >>> df = pd.DataFrame({'animal': ['alligator', 'bee', 'falcon', 'lion',
    ...                    'monkey', 'parrot', 'shark', 'whale', 'zebra']})
    >>> df
          animal
    0  alligator
    1        bee
    2     falcon
    3       lion
    4     monkey
    5     parrot
    6      shark
    7      whale
    8      zebra

    Viewing the first 5 lines

    >>> df.head()
          animal
    0  alligator
    1        bee
    2     falcon
    3       lion
    4     monkey

    Viewing the first `n` lines (three in this case)

    >>> df.head(3)
          animal
    0  alligator
    1        bee
    2     falcon

    For negative values of `n`

    >>> df.head(-3)
          animal
    0  alligator
    1        bee
    2     falcon
    3       lion
    4     monkey
    5     parrot

In [4]:
# Select top N number of records (default = 5)
df.head(n = 5)

,Month,Starting Balance,Repayment,Interest Paid,Principal Paid,New Balance,term,interest_rate,car_type
0,missing,34689.96,687.23,202.93,484.30,34205.66,60,0.0702,Toyota Sienna
1,2,34205.66,687.23,200.10,487.13,33718.53,60,0.0702,Toyota Sienna
2,3,33718.53,687.23,197.25,489.98,33228.55,60,0.0702,Toyota Sienna
3,4,33228.55,687.23,194.38,492.85,32735.70,60,0.0702,Toyota Sienna
4,5,32735.70,687.23,191.50,495.73,32239.97,60,0.0702,Toyota Sienna

In [5]:
# Select bottom N number of records (default = 5)
df.tail()

,Month,Starting Balance,Repayment,Interest Paid,Principal Paid,New Balance,term,interest_rate,car_type
403,56,3951.11,796.01,9.54,786.47,3164.64,60,0.029,VW Golf R
404,57,3164.64,796.01,7.64,788.37,2376.27,60,0.029,VW Golf R
405,58,2376.27,796.01,5.74,790.27,1586.00,60,0.029,VW Golf R
406,59,1586.00,796.01,3.83,792.18,793.82,60,0.029,VW Golf R
407,60,793.82,796.01,1.91,794.10,-0.28,60,0.029,VW Golf R

### Check the column data types

In [6]:
#df['Month'] = df['Month'].astype(str)

In [7]:
df.head()

,Month,Starting Balance,Repayment,Interest Paid,Principal Paid,New Balance,term,interest_rate,car_type
0,missing,34689.96,687.23,202.93,484.30,34205.66,60,0.0702,Toyota Sienna
1,2,34205.66,687.23,200.10,487.13,33718.53,60,0.0702,Toyota Sienna
2,3,33718.53,687.23,197.25,489.98,33228.55,60,0.0702,Toyota Sienna
3,4,33228.55,687.23,194.38,492.85,32735.70,60,0.0702,Toyota Sienna
4,5,32735.70,687.23,191.50,495.73,32239.97,60,0.0702,Toyota Sienna

In [8]:
1 + 2 + 3

6

In [9]:
'1' + '2' + '3'

'123'

In [11]:
df.dtypes

Month                object
Starting Balance    float64
Repayment           float64
Interest Paid       float64
Principal Paid      float64
New Balance         float64
term                  int64
interest_rate       float64
car_type             object
dtype: object

In [12]:
df['Month'].sum()

TypeError: can only concatenate str (not "int") to str

In [ ]:
# Check the column data types using the dtypes attribute
# For example, you can wrongly assume the values in one of your columns is 
# a int64 instead of a string. 
df.dtypes

In [ ]:
# Use the shape attribute to get the number of rows and columns in your dataframe
df.shape

In [ ]:
# The info method gives the column datatypes + number of non-null values
# Notice that we seem to have 408 non-null values for all but the Interest Paid column. 
df.info()