In [1]:
# Import libraries
import pandas as pd
import numpy as np

In [2]:
# Load Excel File
filename = 'data/car_financing.xlsx'
df = pd.read_excel(filename)

### Filtering Data
Filter out the data to only have data `car_type` of 'Toyota Sienna' and `interest_rate` of 0.0702.

In [3]:
df.head()

,Month,Starting Balance,Repayment,Interest Paid,Principal Paid,New Balance,term,interest_rate,car_type
0,1,34689.96,687.23,202.93,484.30,34205.66,60,0.0702,Toyota Sienna
1,2,34205.66,687.23,200.10,487.13,33718.53,60,0.0702,Toyota Sienna
2,3,33718.53,687.23,197.25,489.98,33228.55,60,0.0702,Toyota Sienna
3,4,33228.55,687.23,194.38,492.85,32735.70,60,0.0702,Toyota Sienna
4,5,32735.70,687.23,191.50,495.73,32239.97,60,0.0702,Toyota Sienna

### car_type filter
Comparison Operator | Meaning
--- | --- 
< | less than
<= | less than or equal to
> | greater than
>= | greater than or equal to
== | equal
!= | not equal

In [4]:
# Let's first start by looking at the car_type column. 
df['car_type'].value_counts()

car_type
VW Golf R         144
Toyota Sienna     120
Toyota Carolla    111
Toyota Corolla     33
Name: count, dtype: int64

In [5]:
# Notice that the filter produces a pandas series of True and False values
car_filter = df['car_type']=='Toyota Sienna'

In [6]:
car_filter.head()

0    True
1    True
2    True
3    True
4    True
Name: car_type, dtype: bool

In [7]:
# Approach 1 using square brackets
# Filter dataframe to get a DataFrame of only 'Toyota Sienna'
df[car_filter].head()

,Month,Starting Balance,Repayment,Interest Paid,Principal Paid,New Balance,term,interest_rate,car_type
0,1,34689.96,687.23,202.93,484.30,34205.66,60,0.0702,Toyota Sienna
1,2,34205.66,687.23,200.10,487.13,33718.53,60,0.0702,Toyota Sienna
2,3,33718.53,687.23,197.25,489.98,33228.55,60,0.0702,Toyota Sienna
3,4,33228.55,687.23,194.38,492.85,32735.70,60,0.0702,Toyota Sienna
4,5,32735.70,687.23,191.50,495.73,32239.97,60,0.0702,Toyota Sienna

In [8]:
# Approach 2 using loc
# Filter dataframe to get a DataFrame of only 'Toyota Sienna'
df.loc[car_filter, :]

,Month,Starting Balance,Repayment,Interest Paid,Principal Paid,New Balance,term,interest_rate,car_type
0,1,34689.96,687.23,202.93,484.30,34205.66,60,0.0702,Toyota Sienna
1,2,34205.66,687.23,200.10,487.13,33718.53,60,0.0702,Toyota Sienna
2,3,33718.53,687.23,197.25,489.98,33228.55,60,0.0702,Toyota Sienna
3,4,33228.55,687.23,194.38,492.85,32735.70,60,0.0702,Toyota Sienna
4,5,32735.70,687.23,191.50,495.73,32239.97,60,0.0702,Toyota Sienna
...,...,...,...,...,...,...,...,...,...
115,56,3133.83,632.47,9.37,623.10,2510.73,60,0.0359,Toyota Sienna
116,57,2510.73,632.47,7.51,624.96,1885.77,60,0.0359,Toyota Sienna
117,58,1885.77,632.47,5.64,626.83,1258.94,60,0.0359,Toyota Sienna
118,59,1258.94,632.47,3.76,628.71,630.23,60,0.0359,Toyota Sienna
119,60,630.23,632.47,1.88,630.59,-0.36,60,0.0359,Toyota Sienna

In [9]:
# Notice that it looks like nothing changed
# This is because we didn't update the dataframe after applying the filter
df['car_type'].value_counts()

car_type
VW Golf R         144
Toyota Sienna     120
Toyota Carolla    111
Toyota Corolla     33
Name: count, dtype: int64

In [10]:
# Filter dataframe to get a DataFrame of only 'Toyota Sienna'
df = df.loc[car_filter, :]

In [11]:
df['car_type'].value_counts()

car_type
Toyota Sienna    120
Name: count, dtype: int64

### interest_rate Filter
Comparison Operator | Meaning
--- | --- 
< | less than
<= | less than or equal to
> | greater than
>= | greater than or equal to
== | equal
!= | not equal

In [12]:
df['interest_rate'].value_counts()

interest_rate
0.0702    60
0.0359    60
Name: count, dtype: int64

In [13]:
# Notice that the filter produces a pandas series of True and False values
df['interest_rate']==0.0702

0       True
1       True
2       True
3       True
4       True
       ...
115    False
116    False
117    False
118    False
119    False
Name: interest_rate, Length: 120, dtype: bool

In [14]:
interest_filter = df['interest_rate']==0.0702

In [ ]:
df = df.loc[interest_filter, :]

In [ ]:
df['interest_rate'].value_counts(dropna = False)

### Combining Filters
In the previous sections, we created `car_filter` and `interest_filter` and used the `loc` command to filter the data by first applying the `car_filter` and then the `interest_filter`. An more concise way to do it is shown below. 

Bitwise Logic Operator | Meaning
--- | --- 
& | and
\| | or
^ | exclusive or
~ | not

In [ ]:
df.loc[car_filter & interest_filter, :]