In [1]:
# Import libraries
import pandas as pd
import numpy as np

In [2]:
# Load Excel File
filename = 'data/car_financing.xlsx'
df = pd.read_excel(filename)

In [3]:
df.head()

,Month,Starting Balance,Repayment,Interest Paid,Principal Paid,New Balance,term,interest_rate,car_type
0,1,34689.96,687.23,202.93,484.30,34205.66,60,0.0702,Toyota Sienna
1,2,34205.66,687.23,200.10,487.13,33718.53,60,0.0702,Toyota Sienna
2,3,33718.53,687.23,197.25,489.98,33228.55,60,0.0702,Toyota Sienna
3,4,33228.55,687.23,194.38,492.85,32735.70,60,0.0702,Toyota Sienna
4,5,32735.70,687.23,191.50,495.73,32239.97,60,0.0702,Toyota Sienna

In [4]:
## Filtering 
car_filter = df['car_type']=='Toyota Sienna'
#interest_filter = df['interest_rate']==0.0702
car_filter

0       True
1       True
2       True
3       True
4       True
       ...
403    False
404    False
405    False
406    False
407    False
Name: car_type, Length: 408, dtype: bool

In [5]:
df.shape

(408, 9)

In [6]:
df.loc[car_filter, :]

,Month,Starting Balance,Repayment,Interest Paid,Principal Paid,New Balance,term,interest_rate,car_type
0,1,34689.96,687.23,202.93,484.30,34205.66,60,0.0702,Toyota Sienna
1,2,34205.66,687.23,200.10,487.13,33718.53,60,0.0702,Toyota Sienna
2,3,33718.53,687.23,197.25,489.98,33228.55,60,0.0702,Toyota Sienna
3,4,33228.55,687.23,194.38,492.85,32735.70,60,0.0702,Toyota Sienna
4,5,32735.70,687.23,191.50,495.73,32239.97,60,0.0702,Toyota Sienna
...,...,...,...,...,...,...,...,...,...
115,56,3133.83,632.47,9.37,623.10,2510.73,60,0.0359,Toyota Sienna
116,57,2510.73,632.47,7.51,624.96,1885.77,60,0.0359,Toyota Sienna
117,58,1885.77,632.47,5.64,626.83,1258.94,60,0.0359,Toyota Sienna
118,59,1258.94,632.47,3.76,628.71,630.23,60,0.0359,Toyota Sienna
119,60,630.23,632.47,1.88,630.59,-0.36,60,0.0359,Toyota Sienna

In [7]:
## Filtering 
car_filter = df['car_type']=='Toyota Sienna'
interest_filter = df['interest_rate']==0.0702
df = df.loc[car_filter & interest_filter, :]

In [8]:
df.head()

,Month,Starting Balance,Repayment,Interest Paid,Principal Paid,New Balance,term,interest_rate,car_type
0,1,34689.96,687.23,202.93,484.30,34205.66,60,0.0702,Toyota Sienna
1,2,34205.66,687.23,200.10,487.13,33718.53,60,0.0702,Toyota Sienna
2,3,33718.53,687.23,197.25,489.98,33228.55,60,0.0702,Toyota Sienna
3,4,33228.55,687.23,194.38,492.85,32735.70,60,0.0702,Toyota Sienna
4,5,32735.70,687.23,191.50,495.73,32239.97,60,0.0702,Toyota Sienna

In [9]:
# Approach 1 dictionary substitution using rename method
df = df.rename(columns={'Starting Balance': 'starting_balance',
                        'Interest Paid': 'interest_paid', 
                        'Principal Paid': 'principal_paid',
                        'New Balance': 'new_balance'})

In [10]:
df.head()

,Month,starting_balance,Repayment,interest_paid,principal_paid,new_balance,term,interest_rate,car_type
0,1,34689.96,687.23,202.93,484.30,34205.66,60,0.0702,Toyota Sienna
1,2,34205.66,687.23,200.10,487.13,33718.53,60,0.0702,Toyota Sienna
2,3,33718.53,687.23,197.25,489.98,33228.55,60,0.0702,Toyota Sienna
3,4,33228.55,687.23,194.38,492.85,32735.70,60,0.0702,Toyota Sienna
4,5,32735.70,687.23,191.50,495.73,32239.97,60,0.0702,Toyota Sienna

In [11]:
# Approach 2 list replacement
# Only changing Month -> month, but we need to list the rest of the columns
df.columns = ['month',
              'starting_balance',
              'Repayment',
              'interest_paid',
              'principal_paid',
              'new_balance',
              'term',
              'interest_rate',
              'car_type']

In [12]:
df.head()

,month,starting_balance,Repayment,interest_paid,principal_paid,new_balance,term,interest_rate,car_type
0,1,34689.96,687.23,202.93,484.30,34205.66,60,0.0702,Toyota Sienna
1,2,34205.66,687.23,200.10,487.13,33718.53,60,0.0702,Toyota Sienna
2,3,33718.53,687.23,197.25,489.98,33228.55,60,0.0702,Toyota Sienna
3,4,33228.55,687.23,194.38,492.85,32735.70,60,0.0702,Toyota Sienna
4,5,32735.70,687.23,191.50,495.73,32239.97,60,0.0702,Toyota Sienna

In [13]:
# Approach 1
# This approach allows you to drop multiple columns at a time 
df = df.drop(columns=['term'])

In [14]:
# Approach 2 use the del command
del df['Repayment']

In [15]:
df.shape

(60, 7)

## Removing or Filling in Missing Data
This is an important subject as before you can graph data, you should make sure you aren't trying to graph some missing values as that can cause an error or misinterpretation of the data.

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             60 non-null     int64
 1   starting_balance  60 non-null     float64
 2   interest_paid     59 non-null     float64
 3   principal_paid    60 non-null     float64
 4   new_balance       60 non-null     float64
 5   interest_rate     60 non-null     float64
 6   car_type          60 non-null     object
dtypes: float64(5), int64(1), object(1)
memory usage: 3.8+ KB

In [17]:
df.shape

(60, 7)

In [18]:
df['interest_paid'].value_counts(dropna = False)

interest_paid
202.93    1
200.10    1
103.55    1
100.13    1
96.70     1
NaN       1
89.77     1
86.27     1
82.76     1
79.22     1
75.67     1
72.09     1
68.49     1
64.87     1
61.23     1
57.57     1
53.88     1
50.18     1
46.45     1
42.70     1
38.93     1
35.14     1
31.33     1
27.49     1
23.63     1
19.75     1
15.84     1
11.91     1
7.96      1
106.94    1
110.32    1
113.67    1
161.72    1
197.25    1
194.38    1
191.50    1
188.60    1
185.68    1
182.75    1
179.80    1
176.83    1
173.84    1
170.84    1
167.82    1
164.78    1
158.65    1
117.01    1
155.56    1
152.45    1
149.32    1
146.17    1
143.01    1
139.82    1
136.62    1
133.40    1
130.16    1
126.90    1
123.62    1
120.33    1
3.99      1
Name: count, dtype: int64

In [19]:
help(df['interest_paid'].value_counts)

Help on method value_counts in module pandas.core.base:

value_counts(normalize: 'bool' = False, sort: 'bool' = True, ascending: 'bool' = False, bins=None, dropna: 'bool' = True) -> 'Series' method of pandas.core.series.Series instance
    Return a Series containing counts of unique values.

    The resulting object will be in descending order so that the
    first element is the most frequently-occurring element.
    Excludes NA values by default.

    Parameters
    ----------
    normalize : bool, default False
        If True then the object returned will contain the relative
        frequencies of the unique values.
    sort : bool, default True
        Sort by frequencies when True. Preserve the order of the data when False.
    ascending : bool, default False
        Sort in ascending order.
    bins : int, optional
        Rather than count values, group them into half-open bins,
        a convenience for ``pd.cut``, only works with numeric data.
    dropna : bool, default True
        Don't include counts of NaN.

    Returns
    -------
    Series

    See Also
    --------
    Series.count: Number of non-NA elements in a Series.
    DataFrame.count: Number of non-NA elements in a DataFrame.
    DataFrame.value_counts: Equivalent method on DataFrames.

    Examples
    --------
    >>> index = pd.Index([3, 1, 2, 3, 4, np.nan])
    >>> index.value_counts()
    3.0    2
    1.0    1
    2.0    1
    4.0    1
    Name: count, dtype: int64

    With `normalize` set to `True`, returns the relative frequency by
    dividing all values by the sum of values.

    >>> s = pd.Series([3, 1, 2, 3, 4, np.nan])
    >>> s.value_counts(normalize=True)
    3.0    0.4
    1.0    0.2
    2.0    0.2
    4.0    0.2
    Name: proportion, dtype: float64

    **bins**

    Bins can be useful for going from a continuous variable to a
    categorical variable; instead of counting unique
    apparitions of values, divide the index in the specified
    number of half-open bins.

    >>> s.value_counts(bins=3)
    (0.996, 2.0]    2
    (2.0, 3.0]      2
    (3.0, 4.0]      1
    Name: count, dtype: int64

    **dropna**

    With `dropna` set to `False` we can also see NaN index values.

    >>> s.value_counts(dropna=False)
    3.0    2
    1.0    1
    2.0    1
    4.0    1
    NaN    1
    Name: count, dtype: int64

### Remove Missing Values
You can remove missing values by using the `dropna` method.

In [21]:
df.isnull()

,month,starting_balance,interest_paid,principal_paid,new_balance,interest_rate,car_type
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False
35,False,False,True,False,False,False,False
36,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False
50,False,False,False,False,False,False,False
51,False,False,False,False,False,False,False
52,False,False,False,False,False,False,False
53,False,False,False,False,False,False,False
54,False,False,False,False,False,False,False
55,False,False,False,False,False,False,False
56,False,False,False,False,False,False,False
57,False,False,False,False,False,False,False
58,False,False,False,False,False,False,False
59,False,False,False,False,False,False,False

In [20]:
df.isnull().sum()

month               0
starting_balance    0
interest_paid       1
principal_paid      0
new_balance         0
interest_rate       0
car_type            0
dtype: int64

In [24]:
False + False + True

1

In [25]:
df[30:40]

,month,starting_balance,interest_paid,principal_paid,new_balance,interest_rate,car_type
30,31,18858.57,110.32,576.91,18281.66,0.0702,Toyota Sienna
31,32,18281.66,106.94,580.29,17701.37,0.0702,Toyota Sienna
32,33,17701.37,103.55,583.68,17117.69,0.0702,Toyota Sienna
33,34,17117.69,100.13,587.10,16530.59,0.0702,Toyota Sienna
34,35,16530.59,96.70,590.53,15940.06,0.0702,Toyota Sienna
35,36,15940.06,NaN,593.99,15346.07,0.0702,Toyota Sienna
36,37,15346.07,89.77,597.46,14748.61,0.0702,Toyota Sienna
37,38,14748.61,86.27,600.96,14147.65,0.0702,Toyota Sienna
38,39,14147.65,82.76,604.47,13543.18,0.0702,Toyota Sienna
39,40,13543.18,79.22,608.01,12935.17,0.0702,Toyota Sienna

In [26]:
# You can drop entire rows if they contain 'any' nans in them or 'all'
# this may not be the best strategy for our dataset
df[30:40].dropna(how = 'any')

,month,starting_balance,interest_paid,principal_paid,new_balance,interest_rate,car_type
30,31,18858.57,110.32,576.91,18281.66,0.0702,Toyota Sienna
31,32,18281.66,106.94,580.29,17701.37,0.0702,Toyota Sienna
32,33,17701.37,103.55,583.68,17117.69,0.0702,Toyota Sienna
33,34,17117.69,100.13,587.10,16530.59,0.0702,Toyota Sienna
34,35,16530.59,96.70,590.53,15940.06,0.0702,Toyota Sienna
36,37,15346.07,89.77,597.46,14748.61,0.0702,Toyota Sienna
37,38,14748.61,86.27,600.96,14147.65,0.0702,Toyota Sienna
38,39,14147.65,82.76,604.47,13543.18,0.0702,Toyota Sienna
39,40,13543.18,79.22,608.01,12935.17,0.0702,Toyota Sienna

### Filling in Missing Values
There are a [variety of ways to fill in missing values](https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html).

In [27]:
# Looking at where missing data is located
df['interest_paid'][30:40]

30    110.32
31    106.94
32    103.55
33    100.13
34     96.70
35       NaN
36     89.77
37     86.27
38     82.76
39     79.22
Name: interest_paid, dtype: float64

In [28]:
# Filling in the nan with a zero is probably a bad idea. 
df['interest_paid'][30:40].fillna(0)

30    110.32
31    106.94
32    103.55
33    100.13
34     96.70
35      0.00
36     89.77
37     86.27
38     82.76
39     79.22
Name: interest_paid, dtype: float64

In [30]:
# back fill in value
df['interest_paid'][30:40].bfill()

30    110.32
31    106.94
32    103.55
33    100.13
34     96.70
35     89.77
36     89.77
37     86.27
38     82.76
39     79.22
Name: interest_paid, dtype: float64

In [32]:
# forward fill in value
df['interest_paid'][30:40].fillna(method='ffill')

/var/folders/lz/bb81r331609dkv26yy15mjlh0000gn/T/ipykernel_29763/3472784216.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['interest_paid'][30:40].fillna(method='ffill')

30    110.32
31    106.94
32    103.55
33    100.13
34     96.70
35     96.70
36     89.77
37     86.27
38     82.76
39     79.22
Name: interest_paid, dtype: float64

In [33]:
# linear interpolation (filling in of values)
df['interest_paid'][30:40].interpolate(method = 'linear')

30    110.320
31    106.940
32    103.550
33    100.130
34     96.700
35     93.235
36     89.770
37     86.270
38     82.760
39     79.220
Name: interest_paid, dtype: float64

In [34]:
# Interest paid before filling in the nan with a value
df['interest_paid'].sum()

6450.2699999999995

In [35]:
# Fill in with the actual value
interest_missing = df['interest_paid'].isna()
df.loc[interest_missing,'interest_paid'] = 93.24

In [36]:
# Interest paid after filling in the nan with a value
df['interest_paid'].sum()

6543.509999999999

In [37]:
# Notice we dont have NaN values in the DataFrame anymore
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             60 non-null     int64
 1   starting_balance  60 non-null     float64
 2   interest_paid     60 non-null     float64
 3   principal_paid    60 non-null     float64
 4   new_balance       60 non-null     float64
 5   interest_rate     60 non-null     float64
 6   car_type          60 non-null     object
dtypes: float64(5), int64(1), object(1)
memory usage: 3.8+ KB

In [38]:
# not null
notNullFilter = ~df['interest_paid'].isnull()

In [39]:
df.loc[notNullFilter, :]

,month,starting_balance,interest_paid,principal_paid,new_balance,interest_rate,car_type
0,1,34689.96,202.93,484.30,34205.66,0.0702,Toyota Sienna
1,2,34205.66,200.10,487.13,33718.53,0.0702,Toyota Sienna
2,3,33718.53,197.25,489.98,33228.55,0.0702,Toyota Sienna
3,4,33228.55,194.38,492.85,32735.70,0.0702,Toyota Sienna
4,5,32735.70,191.50,495.73,32239.97,0.0702,Toyota Sienna
5,6,32239.97,188.60,498.63,31741.34,0.0702,Toyota Sienna
6,7,31741.34,185.68,501.55,31239.79,0.0702,Toyota Sienna
7,8,31239.79,182.75,504.48,30735.31,0.0702,Toyota Sienna
8,9,30735.31,179.80,507.43,30227.88,0.0702,Toyota Sienna
9,10,30227.88,176.83,510.40,29717.48,0.0702,Toyota Sienna
10,11,29717.48,173.84,513.39,29204.09,0.0702,Toyota Sienna
11,12,29204.09,170.84,516.39,28687.70,0.0702,Toyota Sienna
12,13,28687.70,167.82,519.41,28168.29,0.0702,Toyota Sienna
13,14,28168.29,164.78,522.45,27645.84,0.0702,Toyota Sienna
14,15,27645.84,161.72,525.51,27120.33,0.0702,Toyota Sienna
15,16,27120.33,158.65,528.58,26591.75,0.0702,Toyota Sienna
16,17,26591.75,155.56,531.67,26060.08,0.0702,Toyota Sienna
17,18,26060.08,152.45,534.78,25525.30,0.0702,Toyota Sienna
18,19,25525.30,149.32,537.91,24987.39,0.0702,Toyota Sienna
19,20,24987.39,146.17,541.06,24446.33,0.0702,Toyota Sienna
20,21,24446.33,143.01,544.22,23902.11,0.0702,Toyota Sienna
21,22,23902.11,139.82,547.41,23354.70,0.0702,Toyota Sienna
22,23,23354.70,136.62,550.61,22804.09,0.0702,Toyota Sienna
23,24,22804.09,133.40,553.83,22250.26,0.0702,Toyota Sienna
24,25,22250.26,130.16,557.07,21693.19,0.0702,Toyota Sienna
25,26,21693.19,126.90,560.33,21132.86,0.0702,Toyota Sienna
26,27,21132.86,123.62,563.61,20569.25,0.0702,Toyota Sienna
27,28,20569.25,120.33,566.90,20002.35,0.0702,Toyota Sienna
28,29,20002.35,117.01,570.22,19432.13,0.0702,Toyota Sienna
29,30,19432.13,113.67,573.56,18858.57,0.0702,Toyota Sienna
30,31,18858.57,110.32,576.91,18281.66,0.0702,Toyota Sienna
31,32,18281.66,106.94,580.29,17701.37,0.0702,Toyota Sienna
32,33,17701.37,103.55,583.68,17117.69,0.0702,Toyota Sienna
33,34,17117.69,100.13,587.10,16530.59,0.0702,Toyota Sienna
34,35,16530.59,96.70,590.53,15940.06,0.0702,Toyota Sienna
35,36,15940.06,93.24,593.99,15346.07,0.0702,Toyota Sienna
36,37,15346.07,89.77,597.46,14748.61,0.0702,Toyota Sienna
37,38,14748.61,86.27,600.96,14147.65,0.0702,Toyota Sienna
38,39,14147.65,82.76,604.47,13543.18,0.0702,Toyota Sienna
39,40,13543.18,79.22,608.01,12935.17,0.0702,Toyota Sienna
40,41,12935.17,75.67,611.56,12323.61,0.0702,Toyota Sienna
41,42,12323.61,72.09,615.14,11708.47,0.0702,Toyota Sienna
42,43,11708.47,68.49,618.74,11089.73,0.0702,Toyota Sienna
43,44,11089.73,64.87,622.36,10467.37,0.0702,Toyota Sienna
44,45,10467.37,61.23,626.00,9841.37,0.0702,Toyota Sienna
45,46,9841.37,57.57,629.66,9211.71,0.0702,Toyota Sienna
46,47,9211.71,53.88,633.35,8578.36,0.0702,Toyota Sienna
47,48,8578.36,50.18,637.05,7941.31,0.0702,Toyota Sienna
48,49,7941.31,46.45,640.78,7300.53,0.0702,Toyota Sienna
49,50,7300.53,42.70,644.53,6656.00,0.0702,Toyota Sienna
50,51,6656.00,38.93,648.30,6007.70,0.0702,Toyota Sienna
51,52,6007.70,35.14,652.09,5355.61,0.0702,Toyota Sienna
52,53,5355.61,31.33,655.90,4699.71,0.0702,Toyota Sienna
53,54,4699.71,27.49,659.74,4039.97,0.0702,Toyota Sienna
54,55,4039.97,23.63,663.60,3376.37,0.0702,Toyota Sienna
55,56,3376.37,19.75,667.48,2708.89,0.0702,Toyota Sienna
56,57,2708.89,15.84,671.39,2037.50,0.0702,Toyota Sienna
57,58,2037.50,11.91,675.32,1362.18,0.0702,Toyota Sienna
58,59,1362.18,7.96,679.27,682.91,0.0702,Toyota Sienna
59,60,682.91,3.99,683.24,-0.33,0.0702,Toyota Sienna

In [40]:
df['interest_paid'][10:20]

10    173.84
11    170.84
12    167.82
13    164.78
14    161.72
15    158.65
16    155.56
17    152.45
18    149.32
19    146.17
Name: interest_paid, dtype: float64