In [1]:
# Import libraries
import pandas as pd
import numpy as np

### Load Excel File

In [2]:
filename = 'data/car_financing.xlsx'
df = pd.read_excel(filename)

## Slicing
1. How to select columns in pandas 
2. How to use slicing operations in pandas

In [3]:
df.head()

,Month,Starting Balance,Repayment,Interest Paid,Principal Paid,New Balance,term,interest_rate,car_type
0,1,34689.96,687.23,202.93,484.30,34205.66,60,0.0702,Toyota Sienna
1,2,34205.66,687.23,200.10,487.13,33718.53,60,0.0702,Toyota Sienna
2,3,33718.53,687.23,197.25,489.98,33228.55,60,0.0702,Toyota Sienna
3,4,33228.55,687.23,194.38,492.85,32735.70,60,0.0702,Toyota Sienna
4,5,32735.70,687.23,191.50,495.73,32239.97,60,0.0702,Toyota Sienna

### Select columns using brackets
With square brackets, you can select one or more columns.

In [4]:
# Select one column using double brackets
df[['car_type']].head()

        car_type
0  Toyota Sienna
1  Toyota Sienna
2  Toyota Sienna
3  Toyota Sienna
4  Toyota Sienna

In [7]:
# Select multiple columns using double brackets
df[['car_type', 'Principal Paid']].head()

        car_type  Principal Paid
0  Toyota Sienna          484.30
1  Toyota Sienna          487.13
2  Toyota Sienna          489.98
3  Toyota Sienna          492.85
4  Toyota Sienna          495.73

In [8]:
# This is a Pandas DataFrame
type(df[['car_type']].head())

pandas.core.frame.DataFrame

In [9]:
# Select one column using single brackets
# This produces a pandas series which is a one-dimensional array which can be labeled
df['car_type'].head()

0    Toyota Sienna
1    Toyota Sienna
2    Toyota Sienna
3    Toyota Sienna
4    Toyota Sienna
Name: car_type, dtype: object

In [10]:
# This is a pandas series
type(df['car_type'].head())

pandas.core.series.Series

In [11]:
df.head()

,Month,Starting Balance,Repayment,Interest Paid,Principal Paid,New Balance,term,interest_rate,car_type
0,1,34689.96,687.23,202.93,484.30,34205.66,60,0.0702,Toyota Sienna
1,2,34205.66,687.23,200.10,487.13,33718.53,60,0.0702,Toyota Sienna
2,3,33718.53,687.23,197.25,489.98,33228.55,60,0.0702,Toyota Sienna
3,4,33228.55,687.23,194.38,492.85,32735.70,60,0.0702,Toyota Sienna
4,5,32735.70,687.23,191.50,495.73,32239.97,60,0.0702,Toyota Sienna

In [12]:
# Keep in mind that you can't select multiple colums using single brackets
# This will result in a KeyError
df['car_type', 'Principal Paid']

KeyError: ('car_type', 'Principal Paid')

In [13]:
df[['car_type', 'Principal Paid']]

          car_type  Principal Paid
0    Toyota Sienna          484.30
1    Toyota Sienna          487.13
2    Toyota Sienna          489.98
3    Toyota Sienna          492.85
4    Toyota Sienna          495.73
..             ...             ...
403      VW Golf R          786.47
404      VW Golf R          788.37
405      VW Golf R          790.27
406      VW Golf R          792.18
407      VW Golf R          794.10

[408 rows x 2 columns]

### Pandas Slicing

With a pandas series, we can select rows using slicing like this: series[start_index:end_index]

The end_index is not inclusive. This behavior is very similar to Python lists.

In [17]:
df['car_type']

0      Toyota Sienna
1      Toyota Sienna
2      Toyota Sienna
3      Toyota Sienna
4      Toyota Sienna
           ...
403        VW Golf R
404        VW Golf R
405        VW Golf R
406        VW Golf R
407        VW Golf R
Name: car_type, Length: 408, dtype: object

In [18]:
df['car_type'][0:10]

0    Toyota Sienna
1    Toyota Sienna
2    Toyota Sienna
3    Toyota Sienna
4    Toyota Sienna
5    Toyota Sienna
6    Toyota Sienna
7    Toyota Sienna
8    Toyota Sienna
9    Toyota Sienna
Name: car_type, dtype: object

In [20]:
# Select column using dot notation. 
# This is not recommended.
df.car_type.head()

0    Toyota Sienna
1    Toyota Sienna
2    Toyota Sienna
3    Toyota Sienna
4    Toyota Sienna
Name: car_type, dtype: object

In [21]:
"""
This won't work as there is a space in the column name. 
Dot notation also fails if your column has the same name 
of a DataFrame's attributes or methods.
"""
df.Principal Paid

SyntaxError: invalid syntax (3765193495.py, line 6)

In [22]:
df['Principal Paid']

0      484.30
1      487.13
2      489.98
3      492.85
4      495.73
        ...
403    786.47
404    788.37
405    790.27
406    792.18
407    794.10
Name: Principal Paid, Length: 408, dtype: float64

### Selecting Columns using loc
The pandas attribute .loc allow you to select columns, index, and slice your data.

In [23]:
# pandas dataframe
df.loc[:, ['car_type']].head()

        car_type
0  Toyota Sienna
1  Toyota Sienna
2  Toyota Sienna
3  Toyota Sienna
4  Toyota Sienna

In [31]:
# pandas series
df.loc[:, ['Month', 'car_type']].head()

   Month       car_type
0      1  Toyota Sienna
1      2  Toyota Sienna
2      3  Toyota Sienna
3      4  Toyota Sienna
4      5  Toyota Sienna